#!/usr/bin/env python
"""Part 2 as a selection test: does MuseCPEval pick the candidate listeners preferred?

Part 2 presented, for one seed, the candidate C ranked first against the candidate a rival
metric ranked first, both regenerated by ACE-Step into the same context.  Nothing here is
a copy of that context, which is the setting the whole paper is about and the one a
reference-based preservation toolkit was never built for.

For each trial we ask which of the two presented candidates MuseCPEval scores higher, then
what share of listeners chose that candidate.  C's own pooled number is computed the same
way from the same ratings, so the two are comparable.

Ties are the midpoint of the five-point scale and are excluded from a win rate, as in
score_ab_session2.py.  Intervals are a cluster bootstrap over SEEDS, because one seed
contributes many rater decisions.

POST HOC, and the output says so: the 80 trials were selected where C and a rival
disagreed by at least 0.03 in C, so this is not a neutral pool of candidates.

Usage (DSP env, from the repo root)::

    python scripts/analysis/musecp_part2.py --out results/musecp/part2.json
"""
import argparse
import csv
import glob
import json
import sys
from pathlib import Path

import numpy as np

_here = Path(__file__).resolve()
try:  # sibling imports across script groups (see scripts/README.md)
    sys.path.insert(0, str(_here.parent.parent))
    import _paths  # noqa: F401
except ImportError:
    pass

DIMS = ["H", "T", "R", "S"]
EPS = 1e-6


def repo_root() -> Path:
    for p in [_here] + list(_here.parents):
        if (p / "CLAUDE.md").exists() or (p / ".git").exists():
            return p
    return _here.parent.parent.parent


def read_csv(path) -> list[dict]:
    with open(path) as fh:
        return list(csv.DictReader(fh))


def cluster_bootstrap(by_seed, n_boot=5000, seed=20260728):
    """Resample SEEDS -> CI on a pooled win rate.  Same estimator as score_ab_session2."""
    rng = np.random.default_rng(seed)
    seeds = sorted(by_seed)
    if len(seeds) < 2:
        return [float("nan"), float("nan")]
    wins = np.array([by_seed[s][0] for s in seeds], float)
    dec = np.array([by_seed[s][1] for s in seeds], float)
    out = []
    for _ in range(n_boot):
        idx = rng.integers(0, len(seeds), len(seeds))
        d = dec[idx].sum()
        if d > 0:
            out.append(wins[idx].sum() / d)
    out = np.array(out)
    return [round(float(np.percentile(out, 2.5)), 4), round(float(np.percentile(out, 97.5)), 4)]


def geo(row, dims=DIMS):
    return float(np.exp(np.mean([np.log(max(float(row[f"score_{d}"]), EPS)) for d in dims])))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", default="results/mos/session2/key.csv")
    ap.add_argument("--responses", default="results/mos/session2/responses/*.json")
    ap.add_argument("--musecp", default="results/musecp/rerank_ace/musecp_metrics.csv")
    ap.add_argument("--scores", default="results/rerank_ace/pair_scores.csv")
    ap.add_argument("--boot", type=int, default=5000)
    ap.add_argument("--out", default="results/musecp/part2.json")
    args = ap.parse_args()
    root = repo_root()

    key = {r["trial_id"]: r for r in read_csv(root / args.key)}
    mcp = {r["pair_id"]: r for r in read_csv(root / args.musecp)}
    murco = {r["pair_id"]: r for r in read_csv(root / args.scores)}
    metrics = [c for c in next(iter(mcp.values())) if c != "pair_id"]
    print(f"{len(key)} trials, {len(mcp)} musecp-scored candidates, {len(metrics)} metrics")

    C = {p: geo(r) for p, r in murco.items()}
    S = {p: float(r["score_S"]) for p, r in murco.items()}

    # ---- ratings -> per-trial (winner_role, n) ----
    files = sorted(glob.glob(str(root / args.responses)))
    ratings = []          # (trial_id, winner_role or None for tie)
    for f in files:
        doc = json.load(open(f))
        for resp in doc.get("responses", []):
            tid = resp["trial_id"]; pref = int(resp["preference"])
            if tid not in key:
                continue
            if pref == 3:
                ratings.append((tid, None)); continue
            side = "A" if pref < 3 else "B"
            role = key[tid][f"opt_{side.lower()}_role"]     # "c" or "rival"
            ratings.append((tid, role))
    print(f"{len(files)} sessions, {len(ratings)} ratings")

    def win_rate(pick_fn, label):
        """Share of DECIDED ratings that chose the candidate pick_fn selects."""
        by_seed, n_tie, n_dec, n_win, n_skip = {}, 0, 0, 0, 0
        for tid, role in ratings:
            k = key[tid]
            chosen = pick_fn(k)                 # "c", "rival" or None (metric is tied)
            if chosen is None:
                n_skip += 1; continue
            if role is None:
                n_tie += 1; continue
            n_dec += 1
            w = 1 if role == chosen else 0
            n_win += w
            s = k["seed"]
            a, b = by_seed.get(s, (0, 0))
            by_seed[s] = (a + w, b + 1)
        out = {"label": label, "n_decided": n_dec, "n_ties": n_tie,
               "n_skipped_metric_tied": n_skip,
               "win_rate": round(n_win / n_dec, 4) if n_dec else None,
               "ci95_cluster_by_seed": cluster_bootstrap(by_seed, args.boot) if by_seed else None,
               "n_seeds": len(by_seed)}
        return out

    report = {"meta": {
        "n_trials": len(key), "n_sessions": len(files), "n_ratings": len(ratings),
        "post_hoc": "The 80 trials were selected where C and a rival disagreed by at "
                    "least 0.03 in C, so this is not a neutral candidate pool. "
                    "MuseCPEval was never proposed by its authors as a selector and "
                    "defines no aggregate; mean12/mean10 are our equal-weight composites.",
        "tie_rule": "midpoint of the five-point scale, excluded from the win rate",
        "sources": {"key": args.key, "musecp": args.musecp, "scores": args.scores}}}

    # ---- 1. reproduce the published per-contrast rows as an assertion ----
    contrasts = {}
    for rival in sorted({r for k in key.values() for r in k["settles"].split(";") if r}):
        sub = [(t, ro) for t, ro in ratings if rival in key[t]["settles"].split(";")]
        by_seed, ties, dec, wins = {}, 0, 0, 0
        for tid, role in sub:
            if role is None:
                ties += 1; continue
            dec += 1; w = 1 if role == "c" else 0; wins += w
            s = key[tid]["seed"]; a, b = by_seed.get(s, (0, 0)); by_seed[s] = (a + w, b + 1)
        contrasts[rival] = {"n_decisions": dec, "n_ties": ties,
                            "win_rate": round(wins / dec, 4) if dec else None,
                            "ci95_cluster_by_seed": cluster_bootstrap(by_seed, args.boot)}
    report["reproduced_contrasts"] = contrasts
    print("\nreproduced Part 2 rows (compare against results/mos/session2/ab_results.json):")
    for k, v in sorted(contrasts.items()):
        print(f"   {k:>12}  n={v['n_decisions']:>4}  ties={v['n_ties']:>3}  "
              f"win {v['win_rate']}  {v['ci95_cluster_by_seed']}")

    # ---- 2. each metric as a selector over the same trials ----
    def picker(table, tol=1e-6):
        def f(k):
            a, b = k["c_pick"], k["rival_pick"]
            if a not in table or b not in table:
                return None
            va, vb = table[a], table[b]
            if not (np.isfinite(va) and np.isfinite(vb)) or abs(va - vb) < tol:
                return None
            return "c" if va > vb else "rival"
        return f

    selectors = {"C": C, "S": S}
    for m in metrics:
        selectors[m] = {p: (float(r[m]) if r[m] != "" else np.nan) for p, r in mcp.items()}

    report["selectors"] = {}
    print("\nselector agreement with listeners (decided ratings):")
    for name, table in selectors.items():
        report["selectors"][name] = win_rate(picker(table), name)
        v = report["selectors"][name]
        if v["win_rate"] is not None:
            print(f"   {name:>18}  {v['win_rate']:.4f}  {v['ci95_cluster_by_seed']}  "
                  f"n={v['n_decided']} (skipped {v['n_skipped_metric_tied']})")

    # ---- 3. does MuseCPEval side with C or with the rival? ----
    agree = {}
    for name in ("musecp_mean12", "musecp_mean10"):
        if name not in selectors:
            continue
        f = picker(selectors[name])
        picks = {t: f(k) for t, k in key.items()}
        agree[name] = {
            "trials_agreeing_with_C": sum(1 for v in picks.values() if v == "c"),
            "trials_agreeing_with_rival": sum(1 for v in picks.values() if v == "rival"),
            "trials_tied_or_unscored": sum(1 for v in picks.values() if v is None)}
        # listener win rate restricted to the trials where it DISAGREES with C
        dis = {t for t, v in picks.items() if v == "rival"}
        sub = [(t, ro) for t, ro in ratings if t in dis and ro is not None]
        if sub:
            n = len(sub); w = sum(1 for _, ro in sub if ro == "rival")
            agree[name]["on_disagreeing_trials"] = {
                "n_trials": len(dis), "n_decided": n,
                "listener_share_choosing_musecp_pick": round(w / n, 4)}
        # The same trials read as a Part 2 table row, in the form the designed arms use:
        # three-way shares over ALL ratings, C's win rate over decided ratings, and the
        # margin (C's share minus the rival's), which equals 2 x (win rate with ties as
        # half) - 1, so its interval is the ties-as-half cluster bootstrap over seeds.
        allsub = [(t, ro) for t, ro in ratings if t in dis]
        if allsub:
            n_all = len(allsub)
            n_c = sum(1 for _, ro in allsub if ro == "c")
            n_r = sum(1 for _, ro in allsub if ro == "rival")
            n_t = n_all - n_c - n_r
            by_seed_dec, by_seed_half = {}, {}
            for t, ro in allsub:
                s = key[t]["seed"]
                a, b = by_seed_half.get(s, (0.0, 0))
                by_seed_half[s] = (a + (1.0 if ro == "c" else 0.5 if ro is None else 0.0), b + 1)
                if ro is not None:
                    a, b = by_seed_dec.get(s, (0, 0))
                    by_seed_dec[s] = (a + (1 if ro == "c" else 0), b + 1)
            lo, hi = cluster_bootstrap(by_seed_half, args.boot)
            agree[name]["as_table_row"] = {
                "note": "C against MuseCPEval on the trials where MuseCPEval prefers the "
                        "rival candidate; post hoc, since no trial was built to settle it",
                "n_ratings": n_all, "n_trials": len(dis),
                "share_C": round(n_c / n_all, 4), "share_tie": round(n_t / n_all, 4),
                "share_rival": round(n_r / n_all, 4),
                "win_rate_decided": round(n_c / (n_c + n_r), 4),
                "ci95_decided_cluster_by_seed": cluster_bootstrap(by_seed_dec, args.boot),
                "margin": round((n_c - n_r) / n_all, 4),
                "ci95_margin_cluster_by_seed": [round(2 * lo - 1, 4), round(2 * hi - 1, 4)],
                "n_seeds": len(by_seed_half)}
    report["agreement_with_C"] = agree
    print("\nwhere MuseCPEval sides:")
    for k, v in agree.items():
        print(f"   {k}: with C {v['trials_agreeing_with_C']}, with rival "
              f"{v['trials_agreeing_with_rival']}, tied {v['trials_tied_or_unscored']}")
        if "on_disagreeing_trials" in v:
            d = v["on_disagreeing_trials"]
            print(f"      on its {d['n_trials']} disagreeing trials listeners chose its "
                  f"pick {d['listener_share_choosing_musecp_pick']:.4f} of {d['n_decided']}")
        if "as_table_row" in v:
            r = v["as_table_row"]
            print(f"      table row: n={r['n_ratings']}  {r['share_C']:.2f}/ {r['share_tie']:.2f}/ "
                  f"{r['share_rival']:.2f}  decided {r['win_rate_decided']:.3f} "
                  f"{r['ci95_decided_cluster_by_seed']}  margin {r['margin']:+.2f} "
                  f"{r['ci95_margin_cluster_by_seed']}")

    # ---- 3b. matched-margin comparison ------------------------------------
    # The 80 pairs were selected because C separated them by at least 0.03 AND a rival
    # ordered them the other way.  MuseCPEval had no part in that, so it is scored on
    # pairs it may barely separate: its median margin is about half of C's when each is
    # expressed as a fraction of that metric's own range over the seed's eight
    # candidates, and on eight pairs it has effectively no opinion.  Applying the SAME
    # margin floor to MuseCPEval puts both metrics on pairs each of them separates.
    # The threshold is swept rather than chosen, because 0.03 is the design's floor for
    # C and nothing makes it the right floor for another metric's scale.
    def restricted(table, keep_trials):
        by_seed, dec, win = {}, 0, 0
        for tid, role in ratings:
            if tid not in keep_trials or role is None:
                continue
            k = key[tid]
            a, b = k["c_pick"], k["rival_pick"]
            va, vb = table.get(a), table.get(b)
            if va is None or vb is None or abs(va - vb) < 1e-9:
                continue
            pick = "c" if va > vb else "rival"
            dec += 1
            w = 1 if role == pick else 0
            win += w
            s = k["seed"]
            x, y = by_seed.get(s, (0, 0))
            by_seed[s] = (x + w, y + 1)
        return {"n_trials": len(keep_trials), "n_decided": dec,
                "win_rate": round(win / dec, 4) if dec else None,
                "ci95_cluster_by_seed": cluster_bootstrap(by_seed, args.boot) if by_seed else None}

    mcp_tab = selectors.get("musecp_mean12", {})
    sweep = {}
    for thr in (0.0, 0.01, 0.02, 0.03, 0.05, 0.08):
        keep = {t for t, k in key.items()
                if abs(mcp_tab.get(k["c_pick"], 0) - mcp_tab.get(k["rival_pick"], 0)) >= thr}
        sweep[f"{thr:.2f}"] = {"musecp_mean12": restricted(mcp_tab, keep),
                               "C": restricted(C, keep)}
    report["matched_margin_sweep"] = {
        "rule": "keep trials where MuseCPEval's own |margin| >= threshold; 0.03 is the "
                "floor the trial builder applied to C, so that row is the matched one",
        "sweep": sweep}
    print("\nmatched-margin sweep (MuseCPEval's own margin floor):")
    print(f"   {'thr':>5}{'trials':>8}{'MuseCPEval':>24}{'C, same trials':>24}")
    for thr, v in sweep.items():
        m, c = v["musecp_mean12"], v["C"]
        print(f"   {thr:>5}{m['n_trials']:>8}   {m['win_rate']!s:>7} {m['ci95_cluster_by_seed']!s:>14}"
              f"   {c['win_rate']!s:>7} {c['ci95_cluster_by_seed']!s:>14}")

    # ---- 4. full-pool ordering agreement, descriptive ----
    from scipy.stats import spearmanr
    by_seed_pool = {}
    for pid in murco:
        by_seed_pool.setdefault(pid.split("::")[0], []).append(pid)
    rho_C, rho_S = [], []
    for s, pids in by_seed_pool.items():
        pids = [p for p in pids if p in mcp]
        if len(pids) < 4:
            continue
        m = np.array([float(mcp[p]["musecp_mean12"]) for p in pids])
        if np.nanstd(m) < 1e-12:
            continue
        rho_C.append(spearmanr(m, [C[p] for p in pids]).statistic)
        rho_S.append(spearmanr(m, [S[p] for p in pids]).statistic)
    report["full_pool_ordering"] = {
        "n_seeds": len(rho_C),
        "spearman_musecp_vs_C": {"mean": round(float(np.nanmean(rho_C)), 4),
                                 "sd": round(float(np.nanstd(rho_C)), 4)},
        "spearman_musecp_vs_S": {"mean": round(float(np.nanmean(rho_S)), 4),
                                 "sd": round(float(np.nanstd(rho_S)), 4)},
        "note": "descriptive: all 8 candidates per seed, not just the two presented"}
    print(f"\nfull-pool Spearman over {len(rho_C)} seeds: "
          f"vs C {report['full_pool_ordering']['spearman_musecp_vs_C']['mean']:+.3f}, "
          f"vs S {report['full_pool_ordering']['spearman_musecp_vs_S']['mean']:+.3f}")

    dest = root / args.out
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(report, indent=1))
    print("\nwrote", dest.relative_to(root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
