#!/usr/bin/env python
"""Artifacts for the two sections where a stated prediction reversed.

Sec. 4.7, the temporal-violation probe. The prediction was that a sequence model would
notice reordering where a time-pooled embedding could not. It went the other way: S is
the blind dimension and CLAP separates the violations perfectly. Emits the full
metric-by-family table so the reversal can be read rather than taken on trust.

Sec. 4.8, the deep horizon. The prediction was that a bounded distance would saturate by
depth 16 while a language model's question would not. That inverted too: CLAP's fall
steepens and S flattens onto a floor. Emits a two-panel figure, because the mechanism is
the collapse of the between-seed spread and a table hides it.

Both read caches that already exist. No GPU, no new audio.

Usage (DSP env):
    python scripts/analysis/reversed_hypotheses.py
    python scripts/analysis/reversed_hypotheses.py --readout singletok
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

ROOT = next((p for p in Path(__file__).resolve().parents
             if (p / ".projectroot").exists() or (p / ".git").exists()),
            Path(__file__).resolve().parent.parent)

# Row order matches the separability matrix of Sec. 3.7 so the two can be read together.
ROWS = [("H", "H (harmonic)"), ("T", "T (timbral)"), ("R", "R (rhythmic)"),
        ("S", "S (structural)"), ("clap_htsat", "CLAP-htsat"),
        ("scs", "SCS (stand-in)"), ("fad_proxy", "FAD (proxy)")]
FAMS = [("shuf_beat", "beat shuffle"), ("shuf_bar", "bar shuffle"), ("rev", "reverse"),
        ("disp_near", "displace near"), ("disp_far", "displace far")]


def temporal_table(analysis: Path, out_tex: Path) -> None:
    d = json.loads(analysis.read_text())
    dt, auc = d["drop_table"], d["control_vs_violation_auc"]

    lines = [
        "% Generated by: python scripts/analysis/reversed_hypotheses.py",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\small",
        "\\caption[The temporal-violation probe]{The temporal-violation probe of "
        "Section~\\ref{sec:temporal}. Mean drop from control per metric and violation "
        "family over 90 tracks, with the control-versus-violation AUC in the last "
        "column.\\\\}",
        "\\label{tab:temporal}",
        "\\begin{tabular}{l" + "r" * (len(FAMS) + 1) + "}",
        "\\toprule",
        "metric & " + " & ".join(lbl for _, lbl in FAMS) + " & AUC \\\\",
        "\\midrule",
    ]
    for i, (key, label) in enumerate(ROWS):
        if key not in auc:
            continue
        if key == "clap_htsat":
            lines.append("\\midrule")
        cells = []
        for fam, _ in FAMS:
            v = dt[fam][key]["mean_drop"]
            cells.append(f"{v:+.3f}")
        a = auc[key]
        lines.append(f"{label} & " + " & ".join(cells) + f" & {a:.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_tex}")
    print(f"  S AUC {auc['S']:.3f} against CLAP-htsat {auc['clap_htsat']:.3f}")


def deep_horizon_figure(htrc: Path, base: Path, stem: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from _figstyle import apply_style, INK, GREY, EDITED, ACCUM
    apply_style()

    H = json.loads(htrc.read_text())
    B = json.loads(base.read_text())
    depths = [1, 2, 4, 8, 16]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(6.4, 2.6))

    # Left: drop from ceiling. The two curves cross, which is the whole point.
    series = [("S", H["S"], EDITED, "$S$", "o"),
              ("clap_htsat", B["clap_htsat"], INK, "CLAP-htsat", "v"),
              ("C", H["C"], ACCUM, "$C$", "s"),
              ("scs", B["scs"], GREY, "SCS stand-in", "P")]
    for _, rec, col, lab, mk in series:
        y = [rec["iters"][str(n)]["drop"] for n in depths]
        ax1.plot(depths, y, marker=mk, ms=3.4, lw=1.2, color=col, label=lab)
    ax1.axvspan(8, 16, color="#f2f2f0", zorder=0)
    ax1.set_xscale("log", base=2)
    ax1.set_xticks(depths); ax1.set_xticklabels(depths)
    ax1.set_xlabel("edit depth")
    ax1.set_ylabel("drop from ceiling")
    ax1.set_title("Nothing flattens past depth eight", fontsize=8.5)
    ax1.legend(fontsize=6.8, frameon=False, loc="lower right")
    ax1.grid(alpha=0.25, lw=0.5)
    ax1.spines[["top", "right"]].set_visible(False)

    # Right: every seed's S, which is where the floor is visible and a mean hides it.
    per = H["S"]["per_seed"]["iters"]
    seeds = sorted(per["1"])
    for s in seeds:
        ax2.plot(depths, [per[str(n)][s] for n in depths],
                 lw=0.8, color=EDITED, alpha=0.5, zorder=1)
    # S takes only two or three distinct values across ten seeds, so the lines lie on top
    # of one another. Size each point by how many seeds share it rather than let the
    # overlap read as missing data.
    import collections
    for n in depths:
        cnt = collections.Counter(round(per[str(n)][s], 3) for s in seeds)
        for val, k in cnt.items():
            ax2.scatter([n], [val], s=6 + 9 * k, facecolor="white",
                        edgecolor=EDITED, linewidth=0.8, zorder=2)
    mean = [np.mean([per[str(n)][s] for s in seeds]) for n in depths]
    ax2.plot(depths, mean, marker="o", ms=3.4, lw=1.4, color=EDITED, zorder=3, label="mean")
    for n in (8, 16):
        sd = float(np.std([per[str(n)][s] for s in seeds]))
        ax2.annotate(f"sd {sd:.3f}", (n, mean[depths.index(n)]),
                     textcoords="offset points", xytext=(-6, 13), fontsize=6.6,
                     color=INK, ha="right" if n == 16 else "center")
    ax2.set_xscale("log", base=2)
    ax2.set_xticks(depths); ax2.set_xticklabels(depths)
    ax2.set_xlabel("edit depth")
    ax2.set_ylabel("$S$, per seed")
    ax2.set_title("Ten seeds, still spread at depth sixteen", fontsize=8.5)
    ax2.grid(alpha=0.25, lw=0.5)
    ax2.spines[["top", "right"]].set_visible(False)

    fig.tight_layout(w_pad=1.4)
    for ext in ("pdf", "png"):
        fig.savefig(f"{stem}.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {stem}.pdf/.png")
    s8, s16 = H["S"]["iters"]["8"], H["S"]["iters"]["16"]
    c8, c16 = B["clap_htsat"]["iters"]["8"], B["clap_htsat"]["iters"]["16"]
    print(f"  S  8->16 {s16['drop'] - s8['drop']:+.3f}  sd {s8['std']:.3f} -> {s16['std']:.3f}")
    print(f"  CLAP 8->16 {c16['drop'] - c8['drop']:+.3f}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--readout", choices=("variants", "singletok"), default="variants",
                    help="which S read-out the Sec. 4.7 table reports; 'variants' is the "
                         "shipped protocol and the one every other result uses")
    ap.add_argument("--tex", default=str(ROOT / "results/diagnostics/temporal.tex"))
    ap.add_argument("--fig", default=str(ROOT / "figures/fig_deep_horizon"))
    a = ap.parse_args()

    name = "analysis.json" if a.readout == "variants" else "analysis_singletok.json"
    temporal_table(ROOT / "results/temporal" / name, Path(a.tex))
    deep_horizon_figure(ROOT / "results/drift/drift_htrc_sao_deep.json",
                        ROOT / "results/drift/drift_baselines_sao_deep.json",
                        Path(a.fig))


if __name__ == "__main__":
    main()
