#!/usr/bin/env python
"""Build the Part-2 (A/B preference) Loop & Merge tables. DSP env, stdlib only.

Part 2 is the head-to-head: 64 trials, each a pair of 12 s clips of the same piece
in which a short middle section was regenerated by an AI model. One option was
chosen by C, the other by a rival metric (CLAP / SCS / C_noS). The rater says
which regenerated section fits its surroundings better.

Block structure is taken from the already-validated local instrument
(results/mos/session2/session2_block*.html): 8 blocks x 32 comparisons, each of
the 64 trials appearing in exactly 4 blocks. Do not regenerate that assignment
here -- it is balanced for position and for rival coverage, and the pilot ran on
it. This script only re-expresses it as Qualtrics loop tables.

THREE fields per row, not two:
  Field 1  trial_id (opaque: t001. Never the seed, role, or which side is C --
           loop fields are visible in the page source and the response export)
  Field 2  Version A audio embed
  Field 3  Version B audio embed

results/mos/session2/key.csv holds the A/B -> C/rival mapping and stays
researcher-side. Uploading it would hand a participant the answer key.

Usage:
  python scripts/mos/make_session2_loops.py
Outputs: results/mos/qualtrics/loop_s2_block<N>_paste.csv (no header row)
"""
import argparse
import csv
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = next((p for p in Path(__file__).resolve().parents
             if (p / ".projectroot").exists() or (p / ".git").exists()),
            Path(__file__).resolve().parent.parent)
EMBED = ('<audio controls preload="none" style="width:100%">'
         '<source src="{host}/CP/File.php?F={fid}" type="audio/mpeg"></audio>')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--blocks-dir", default="results/mos/session2")
    ap.add_argument("--trials", default="results/mos/session2/trials.csv")
    ap.add_argument("--ids", default="results/mos/qualtrics/file_ids.csv")
    ap.add_argument("--out-dir", default="results/mos/qualtrics")
    ap.add_argument("--host", default="https://qualtrics.ucl.ac.uk")
    args = ap.parse_args()

    ids = {r["filename"]: r["file_id"]
           for r in csv.DictReader(open(ROOT / args.ids))}
    trials = {r["trial_id"]: r for r in csv.DictReader(open(ROOT / args.trials))}

    sources = sorted((ROOT / args.blocks_dir).glob("session2_block*.html"),
                     key=lambda p: int(re.search(r"block(\d+)", p.stem).group(1)))
    if not sources:
        sys.exit(f"no session2_block*.html under {args.blocks_dir}")

    seen = Counter()
    out_dir = ROOT / args.out_dir
    for src in sources:
        n = re.search(r"block(\d+)", src.stem).group(1)
        # order of first appearance in the html IS the block's trial order; Qualtrics
        # randomises presentation per participant anyway, so only membership matters.
        order, ids_in = [], set()
        for tid in re.findall(r"(t\d{3})_A\.mp3", src.read_text()):
            if tid not in ids_in:
                ids_in.add(tid)
                order.append(tid)

        rows = []
        for tid in order:
            t = trials.get(tid)
            if t is None:
                sys.exit(f"block {n}: {tid} is not in trials.csv")
            missing = [f for f in (t["file_a"], t["file_b"]) if f not in ids]
            if missing:
                sys.exit(f"block {n}: {missing} absent from {args.ids} — re-harvest the library")
            rows.append([tid,
                         EMBED.format(host=args.host, fid=ids[t["file_a"]]),
                         EMBED.format(host=args.host, fid=ids[t["file_b"]])])
            seen[tid] += 1

        dest = out_dir / f"loop_s2_block{n}_paste.csv"
        with dest.open("w", newline="") as fh:
            csv.writer(fh).writerows(rows)
        print(f"  {dest.name}: {len(rows)} comparisons")

    reps = Counter(seen.values())
    print(f"\n{len(sources)} blocks | {len(seen)} unique trials | "
          f"appearances per trial: {dict(reps)}")
    if len(reps) != 1:
        print("  WARNING: trials are not equally replicated across blocks")
    print("Never upload results/mos/session2/key.csv — it maps A/B to C vs rival.")


if __name__ == "__main__":
    main()
