#!/usr/bin/env python
"""Build session 2: C vs rival metrics, two players, 5-point preference. DSP env.

Consumes `select_ab_trials.py` output. For each trial, cuts a 12 s excerpt from each
of the two candidates and renders a blinded A/B comparison.

Why 0-12 s: the regenerated region is 5-8 s of the 30 s candidate, so this window
carries 5 s of lead-in, the edit itself, and 4 s of resolution. The full 30 s track
doubles session length to hear mostly untouched audio.

Fairness details that decide whether the result means anything:
  - the two options are RMS-matched TO EACH OTHER, then peak-safe scaled together.
    A loudness difference between arms would be a preference cue that has nothing to
    do with coherence, and C's pick has no reason to be the louder one.
  - option A/B assignment is randomised per trial from a fixed seed, so which arm is
    C's pick is unpredictable to the rater but reproducible for the analyst.
  - the key (which option was C's, which contrasts the trial settles) is written to a
    SEPARATE file that never reaches the participant.

Scale matches the existing rerank A/B pilot so its numbers stay comparable:
  1 = A clearly better ... 3 = about the same ... 5 = B clearly better

Usage:
  python scripts/mos/prepare_ab_session2.py
  python scripts/mos/prepare_ab_session2.py --secs 12 --out-dir results/mos/session2
Outputs: <out-dir>/audio/*.mp3, trials.csv, key.csv, session2.html
"""
import argparse
import csv
import glob
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import librosa
import numpy as np
import soundfile as sf

ROOT = next((p for p in Path(__file__).resolve().parents
             if (p / ".projectroot").exists() or (p / ".git").exists()),
            Path(__file__).resolve().parent.parent)
SR = 48000
EPS = 1e-8

PAGE = """<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Listening study — session 2</title>
<style>
 body{font-family:system-ui,-apple-system,sans-serif;max-width:44rem;margin:0 auto;
      padding:1.5rem;line-height:1.55;color:#111}
 .card{border:1px solid #ddd;border-radius:10px;padding:1.25rem;margin:1rem 0}
 .opt{border:1px solid #ccc;border-radius:10px;padding:.9rem;margin:.6rem 0;background:#fafafa}
 .opt b{font-size:1.05rem}
 audio{width:100%%;margin-top:.4rem}
 button{font-size:1rem;padding:.55rem 1.1rem;border-radius:8px;border:1px solid #888;
        background:#f6f6f6;cursor:pointer}
 button:disabled{opacity:.45;cursor:not-allowed}
 .scale{display:flex;flex-direction:column;gap:.4rem;margin:1rem 0}
 .scale label{display:flex;align-items:baseline;gap:.6rem;border:1px solid #bbb;
              border-radius:8px;padding:.55rem .8rem;cursor:pointer}
 .scale label:has(input:checked){background:#e8f0fe;border-color:#3367d6}
 .prog{color:#666;font-size:.9rem}
 .warn{background:#fff8e1;border-color:#f0c36d}
</style></head><body>
<div id="app"></div>
<script>
const TRIALS = %(trials)s;
const AUDIO = "audio";
const SCALE = [
 {v:1, t:"Version A is clearly more coherent"},
 {v:2, t:"Version A is slightly more coherent"},
 {v:3, t:"About the same"},
 {v:4, t:"Version B is slightly more coherent"},
 {v:5, t:"Version B is clearly more coherent"},
];
const app=document.getElementById("app");
const code="s2-"+Math.random().toString(36).slice(2,8);
let answers={}, ms={}, i=0, t0=0;   // answers[idx] = 1..5 | 'skip'
function shuffle(a){for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));
 [a[j],a[k]]=[a[k],a[j]];}return a;}
const order=shuffle(TRIALS.slice());

function intro(){
 app.innerHTML=`<h2>Listening study — part 2</h2>
 <div class="card warn"><b>Local dry run.</b> No participant data is collected here.</div>
 <div class="card">
  <p>In each trial you hear <b>two versions of the same piece of music</b>. In both, a
  short section in the middle was <b>regenerated by an AI model</b>. The surrounding
  music is identical — only the regenerated section differs.</p>
  <p>Your job: decide <b>which version's regenerated section fits better with the music
  around it</b> — in key, style, tempo and instrumentation. Listen to both before
  answering; you can replay either as often as you like.</p>
  <p><b>Before you start — set your volume.</b> Some of this audio is machine-generated
  and may sound harsh or distorted. Set a comfortable level and leave it there. If any
  comparison is uncomfortable, every trial has a <b>Skip</b> button.</p>
  <p class="prog">${order.length} comparisons, about ${Math.round(order.length*0.75)} minutes.</p>
  <button onclick="start()">Start</button></div>`;
}
function start(){ i=0; trial(); }
function trial(){
 const t=order[i];
 app.innerHTML=`<p class="prog">Comparison ${i+1} of ${order.length}</p>
 <div class="card">
  <div class="opt"><b>Version A</b>
   <audio controls preload="none" src="${AUDIO}/${t.file_a}"></audio></div>
  <div class="opt"><b>Version B</b>
   <audio controls preload="none" src="${AUDIO}/${t.file_b}"></audio></div>
  <p><b>Which version's regenerated section fits better with the surrounding music?</b></p>
  <p class="prog">Both versions share the same surrounding music — only the middle
  section differs. Judge how well that middle section matches the rest in
  <b>key, style, tempo and instrumentation</b>. Not which track you prefer, and not
  which is louder or cleaner overall.</p>
  <div class="scale">${SCALE.map(s=>`<label><input type="radio" name="p" value="${s.v}">
    <span>${s.t}</span></label>`).join("")}</div>
  <button id="bk" onclick="back()" ${i===0?'disabled':''}>Back</button>
  <button id="nx" disabled onclick="submit()">Next</button>
  <button onclick="skip()">Skip — uncomfortable</button>
 </div>`;
 t0=performance.now();
 const prev=answers[i];
 if(prev && prev!=='skip'){
   const el=document.querySelector(`input[name=p][value="${prev}"]`);
   if(el){ el.checked=true; document.getElementById("nx").disabled=false; }
 }
 document.querySelectorAll('input[name=p]').forEach(el=>el.addEventListener("change",
   ()=>{document.getElementById("nx").disabled=false;}));
}

function back(){ if(i>0){ i--; trial(); } }
function skip(){ answers[i]='skip'; i++; if(i<order.length) trial(); else done(); }
function submit(){
 const cur=document.querySelector('input[name=p]:checked'); if(!cur) return;
 answers[i]=parseInt(cur.value); ms[i]=Math.round(performance.now()-t0);
 i++; if(i<order.length) trial(); else done();
}

function collect(){   // built at the end so Back-and-change is reflected
 const out=[];
 order.forEach((t,k)=>{
   const a=answers[k]; if(a===undefined) return;
   if(a==='skip'){ out.push({session_code:code, trial_id:t.trial_id, preference:null,
                             skipped:true}); return; }
   out.push({session_code:code, trial_id:t.trial_id, preference:a, ms_to_respond:ms[k]});
 });
 return out;
}
function done(){
 const responses=collect();
 const nSkip=responses.filter(r=>r.skipped).length;
 const blob=new Blob([JSON.stringify({session_code:code, dry_run:true,
   generated:new Date().toISOString(), n_skipped:nSkip, responses},null,1)],
   {type:"application/json"});
 app.innerHTML=`<h2>Done</h2><div class="card">
 <p>${responses.length-nSkip} comparisons, ${nSkip} skipped.</p>
 <p><a href="${URL.createObjectURL(blob)}" download="ab_${code}.json">Download ab_${code}.json</a>
 — score with <code>scripts/mos/score_ab_session2.py</code>.</p></div>`;
}
intro();
</script></body></html>
"""


def excerpt(path, secs):
    y, _ = librosa.load(str(path), sr=SR, mono=True, offset=0.0, duration=secs)
    return y.astype("float32")


def encode(y, out_path):
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=True) as tmp:
        sf.write(tmp.name, y, SR)
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", tmp.name,
                        "-codec:a", "libmp3lame", "-b:a", "192k", str(out_path)], check=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trials", default="results/rerank_ace/ab_trials.json")
    ap.add_argument("--candidates", default="results/rerank_ace/candidates")
    ap.add_argument("--out-dir", default="results/mos/session2")
    ap.add_argument("--secs", type=float, default=12.0)
    ap.add_argument("--block-size", type=int, default=24,
                    help="comparisons per participant (~15 min); 0 = one page with all trials")
    ap.add_argument("--n-blocks", type=int, default=8)
    ap.add_argument("--seed", type=int, default=20260728)
    ap.add_argument("--force", action="store_true",
                    help="regenerate over an existing key.csv. Only safe before any "
                         "responses have been collected against it.")
    args = ap.parse_args()

    spec = json.load(open(ROOT / args.trials))
    rng = np.random.default_rng(args.seed)
    out = ROOT / args.out_dir

    # key.csv is a record of a study that has already run, not a build artefact.  It maps
    # each trial's option A/B onto C and the rival, and the 40 collected response files
    # carry only trial_id plus a 1-5 preference, so their meaning lives entirely here.  A
    # regeneration with a different --seed, or from a changed candidate pool, would
    # reassign those roles and silently invert answers that are already on disk.  Refuse
    # by default, and check before the expensive audio work rather than after it.
    key_path = out / "key.csv"
    if key_path.exists() and not args.force:
        n_resp = len(glob.glob(str(out / "responses" / "*.json")))
        print(f"refusing to overwrite {key_path}", file=sys.stderr)
        print(f"  it already exists and {n_resp} response file(s) sit beside it; "
              f"rewriting it would re-randomise which option was C's pick.", file=sys.stderr)
        print(f"  pass --force if no responses have been collected yet, or write to a "
              f"different --out-dir.", file=sys.stderr)
        return 1

    (out / "audio").mkdir(parents=True, exist_ok=True)

    # Position of C's pick is BALANCED, not left to chance: listeners carry a position
    # bias (commonly toward whichever they heard last), and if that bias correlated with
    # which arm is C's it would land straight in the headline number. Exactly half the
    # trials show C's pick first; the order is shuffled so it is still unpredictable.
    n_trials = len(spec["trials"])
    c_first = np.array([True] * (n_trials // 2) + [False] * (n_trials - n_trials // 2))
    rng.shuffle(c_first)

    rows, key, missing = [], [], []
    for n, t in enumerate(spec["trials"], 1):
        tid = f"t{n:03d}"
        srcs = {}
        ok = True
        for role, pid in (("c", t["c_pick"]), ("rival", t["rival_pick"])):
            p = ROOT / args.candidates / (pid.replace("::", "_") + ".wav")
            if not p.is_file():
                ok = False
                missing.append(str(p.relative_to(ROOT)))
            else:
                srcs[role] = excerpt(p, args.secs)
        if not ok:
            continue

        # blind: map {C's pick, rival's pick} -> {A, B} per the balanced schedule
        roles = ["c", "rival"] if c_first[n - 1] else ["rival", "c"]
        ya, yb = srcs[roles[0]], srcs[roles[1]]
        n_s = min(len(ya), len(yb))
        ya, yb = ya[:n_s], yb[:n_s]
        # match B's level to A, then scale the PAIR together so neither is louder
        ra = np.sqrt(np.mean(ya ** 2)) + EPS
        rb = np.sqrt(np.mean(yb ** 2)) + EPS
        yb = yb * (ra / rb)
        peak = max(float(np.max(np.abs(ya))), float(np.max(np.abs(yb))), EPS)
        g = min(0.1 / ra, 0.99 / peak)          # common target RMS, never clipping
        ya, yb = (ya * g).astype("float32"), (yb * g).astype("float32")

        fa, fb = f"{tid}_A.mp3", f"{tid}_B.mp3"
        encode(ya, out / "audio" / fa)
        encode(yb, out / "audio" / fb)
        rows.append({"trial_id": tid, "file_a": fa, "file_b": fb})
        key.append({"trial_id": tid, "seed": t["seed"],
                    "opt_a_role": roles[0], "opt_b_role": roles[1],
                    "c_pick": t["c_pick"], "rival_pick": t["rival_pick"],
                    "c_margin": t["c_margin"], "settles": ";".join(t["settles"])})

    with open(out / "trials.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["trial_id", "file_a", "file_b"])
        w.writeheader()
        w.writerows(rows)
    # Carry over any columns a later analysis added to key.csv (musecp_pick, say).  They
    # are keyed by trial_id and this script knows nothing about them, so without this a
    # --force rebuild would drop them without a word.
    fields = list(key[0].keys())
    if key_path.exists():
        with open(key_path, newline="") as fh:
            prev = {r["trial_id"]: r for r in csv.DictReader(fh)}
        extra = [c for c in (next(iter(prev.values())) if prev else {}) if c not in fields]
        if extra:
            print(f"carrying over {len(extra)} added column(s) in key.csv: "
                  f"{', '.join(extra)}")
            fields += extra
            for row in key:
                for c in extra:
                    row[c] = prev.get(row["trial_id"], {}).get(c, "")
    with open(key_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(key)

    # Blocks: 64 comparisons is ~32 min, longer than session 1 and more than the
    # amendment should declare. Deal the trials round-robin into overlapping blocks so
    # every comparison is covered the same number of times -- no trial may end up with
    # systematically fewer ratings than its neighbours.
    from collections import Counter
    blocks = {}
    if args.block_size and args.block_size < len(rows):
        # Deal each trial's repeats into DISTINCT blocks, filling emptiest blocks first.
        # The old approach concatenated shuffled copies of the trial list and sliced fixed
        # windows; because len(rows) need not divide block_size, a window could straddle a
        # copy boundary and draw the same trial twice, so one participant rated the
        # identical comparison twice in a session and the trial lost a block of coverage.
        need = args.n_blocks * args.block_size
        reps, extra = divmod(need, len(rows))
        cap = [args.block_size] * args.n_blocks
        bl = [[] for _ in range(args.n_blocks)]
        seen = [set() for _ in range(args.n_blocks)]
        order = rows[:]
        rng.shuffle(order)
        # trials getting one extra appearance, when need is not an exact multiple
        bonus = set(t["trial_id"] for t in order[:extra])
        for tr in order:
            want = reps + (1 if tr["trial_id"] in bonus else 0)
            for b in sorted(range(args.n_blocks), key=lambda i: (-cap[i], i)):
                if want == 0:
                    break
                if cap[b] > 0 and tr["trial_id"] not in seen[b]:
                    bl[b].append(tr)
                    seen[b].add(tr["trial_id"])
                    cap[b] -= 1
                    want -= 1
            if want:
                print(f"  WARNING: trial {tr['trial_id']} placed only "
                      f"{reps - want}/{reps} times")
        for b in range(args.n_blocks):
            rng.shuffle(bl[b])
            blocks[f"block{b+1}"] = bl[b]
    else:
        blocks["all"] = rows

    for name, bl in blocks.items():
        (out / f"session2_{name}.html").write_text(
            PAGE % {"trials": json.dumps(bl)}, encoding="utf-8")
    cover = Counter(t["trial_id"] for bl in blocks.values() for t in bl)
    per_trial = [cover.get(r["trial_id"], 0) for r in rows]

    print(json.dumps({
        "trials": len(rows), "secs": args.secs,
        "per_contrast": dict(Counter(c for k in key for c in k["settles"].split(";"))),
        "c_pick_shown_as_A": sum(1 for k in key if k["opt_a_role"] == "c"),
        "blocks": {n: len(b) for n, b in blocks.items()},
        "blocks_per_trial": {"min": min(per_trial), "max": max(per_trial)},
        "est_minutes_per_participant": round(args.block_size * (2 * args.secs + 6) / 60, 1)
        if args.block_size else None,
        "missing_candidates": missing[:4], "n_missing": len(missing),
        "out_dir": str(out),
    }, indent=1))
    print("\nkey.csv is researcher-only — it says which option was C's pick.")


if __name__ == "__main__":
    raise SystemExit(main())
